:sunrise_over_mountains:

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,14 +1,36 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require 'fileutils'
 
-set -e
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-cp .env.sample .env
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-bundle check || bundle install
+FileUtils.chdir APP_ROOT do
+  # This script is a way to setup or update your development environment automatically.
+  # This script is idempotent, so that you can run it at anytime and get an expectable outcome.
+  # Add necessary setup steps to this file.
 
-bundle exec rake db:create || true
-bundle exec rake db:migrate
-bundle exec rake db:seed
-bundle exec rake db:test:prepare
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-echo "You're good to go. Run bin/server to get the app running."
+  # Install JavaScript dependencies
+  # system('bin/yarn')
+
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   FileUtils.cp 'config/database.yml.sample', 'config/database.yml'
+  # end
+
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:prepare'
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
