Update Rails: 5.1.4 -> 5.2.0

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,33 +1,36 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require 'fileutils'
+include FileUtils
 
-set -Eeuo pipefail
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-BASE_DIR=$(dirname "${BASH_SOURCE[0]:-$0}")
-cd "${BASE_DIR}/.." || exit 127
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# shellcheck source=../scripts/logging.sh
-. scripts/logging.sh
-# shellcheck source=../scripts/utils.sh
-. scripts/utils.sh
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
 
-log_info "setup" "Setting up the .env..."
-if [ ! -f .env ]; then
-  cp .env.sample .env
-  log_success ".env file created, you might want to open .env and set the
-    correct values. Make sure you export them into your environment before
-    runing this script again."
-  exit
-else
-  log_warn ".env file already exists, skipping..."
-fi
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-log_info "setup" "Installing dependencies..."
-bundle check || bundle install
+  # Install JavaScript dependencies if using Yarn
+  # system('bin/yarn')
 
-log_info "setup" "Configuring database and running migrations..."
-bundle exec rake db:create || true
-bundle exec rake db:migrate
-bundle exec rake db:seed
-bundle exec rake db:test:prepare
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   cp 'config/database.yml.sample', 'config/database.yml'
+  # end
 
-log_info "You're good to go. Run bin/server to get the app running."
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
